# -*- coding: utf-8 -*-
"""HEPSF_Notebook1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xb9gw0viLNYZM8PWyzOxzpb46ccxPmHj

# Mi primera simulación del LHC en Pythia 🚀
Author: A. Ramirez-Morales (andres.ramirez.morales@cern.ch)

## Instrucciones:
- Lea cuidadosamente las explicaciones
- Comente las líneas de código donde se indique explicando claro y breve la función de dicha línea
- Resolver los ejercicios al final del Notebook
- Consulte la página oficial de Pythia8: https://pythia.org/




## Primero, instalemos Pythia en nuestro entorno
"""

# ejecuta esta celta con el botón de play de la izquierda
!pip install pythia8mc

"""# ¿Qué es Pythia?

Pythia es un generador de eventos para física de partículas. Es un programa de computadora que simula colisiones de partículas (como las que ocurren en el LHC del CERN) y predice qué partículas se producirán y cómo se moverán.

# ¿Para qué sirve?
Queremos estudiar colisiones de partículas pero:

- No tienes acceso a un acelerador (cuestan miles de millones de euros 🤡)
- No puedes hacer un experimento cada vez que tienes una idea nueva
- Necesitas comparar tus teorías con datos reales

Nos falta aura!! **Solución:** Usar Pythia para simular las colisiones en la computadora. Pythia es un simulador de eventos **Monte Carlo** [https://aws.amazon.com/es/what-is/monte-carlo-simulation/]

# Paso 1: Cargar las librerías necesarias
"""

# ejecute esta celda para cargar las librerías
import pythia8mc
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from matplotlib import rcParams
import math

# Configuración de gráficos
rcParams['font.size'] = 12
sns.set_style("whitegrid")

"""# Paso 2: Configurar con las opciones de Pythia
El proceso que vamos a simular es $pp→Z→e^-e^+$, es decir la **colisión** de dos protones, que despues **producen** un bosón Z y este bosón **decae** a un electrón y un positrón, todo dentro del LHC
### Antes de revisar el código, respondamos las siguientes preguntas:
- ¿A qué energía colisionan los protones en el LHC?
- ¿Cuál es la masa experimental del bosón Z
- ¿Qué significa `pdgID` o número de partícula en simulaciones Monte Carlo?
"""



# ejecute esta celda, y comente las lineas indicadas procurando dar una explicacion

pythia = pythia8mc.Pythia()

pythia.readString("Beams:idA = 11")    # se identifica un haz de protones
pythia.readString("Beams:idB = -11")    # se identifica un haz de protones
pythia.readString("Beams:eCM = 14000")   # nos indica la energía del centro de masa de una colisión

# activar nuestro proceso de interés
pythia.readString("WeakSingleBoson:ffbar2gmZ = on")  # activa la producción de un bosón virtual a partir de la aniquilación o interacción de un par quark-antiquark

# inicializar Pythia
pythia.init()

"""# Paso 3: Hacer la simulación

### Queremos entender como funciona Pythia hace la simulación de eventos, para ello, debemos plantearnos las siguientes preguntas:

- En Pythia, ¿qué significa un evento(`event`)?
R= Representa la simulación de una colisión de partículas
- En Pythia, qué significa una partícula (`particle`)?
R= Un registro detallado de cualquier entidad cuántica o estado intermedio generado durante la simulación de una colisión
- Aquí, ¿que significa madre (`mother`), hija (`daughter`)?
R= mother representa una partícula  de origen a partir de la cual se genera otra partícula, daughter es una partícula que surge a partir de la desintegración de otra partícula previa
- ¿Qué unidades de masa, momento y energía se adoptan en Pythia?
R= GeV
- ¿Qué es lo que nos interesa almacenar después de que terminamos la simulación?
R= Los cuadrimomentos de las partículas de mi interés
"""

# Ejecute el código de esta celda y agregue comentarios donde se indique

# aqui preparamos las variables donde almacenaremos la información de interés
# electron
pT_e = []
# positron
pT_pos = []
# bosón Z
reconstructed_Z_masses = []
z_mass_og = []
z_pt_og = []


# generate events
n_events = 1000
for i in range(n_events):
    if not pythia.next():
        continue
    z_boson_found = False
    for particle in pythia.event:
        if particle.id() == 23:  # Z boson
            # check if the Z boson mass is within a certain range
            z_mass = particle.m()
            if abs(z_mass - 91.1876) < 10.0:  # aqui se obtiene la masa de la partícula
                z_boson_found = True
                mass_z = particle.p().mCalc()
                break # salir del bucle en el que estoy

    if not z_boson_found:
        continue
    electrons_found = []
    positrons_found = []
    for i in range(pythia.event.size()):
        particle = pythia.event[i]
        if particle.id() == 11:  # electron
            mother = particle.mother1()
            if pythia.event[mother].id() == 23:  # indica la primera partícula madre de electrones
                electrons_found.append(particle)
        elif particle.id() == -11:  # positron
            mother = particle.mother1()
            if pythia.event[mother].id() == 23:  # pregunta si la madre de la partícula es un bosón Z
                positrons_found.append(particle)

    # se toma el electrón y el positrón y se comprueba que vienen del mismo bosón Z
    for electron in electrons_found:
        for positron in positrons_found:
            if electron.mother1() == positron.mother1(): # devuelve el índice de la primera madre de la partícula.
                # get electron kinematics
                pElectron = electron.p() # devuelve el cuatro-momento del electrón:
                pT_e.append(pElectron.pT()) # calcula el momento transversal:

                # get positron kinematics
                pPositron = positron.p()
                pT_pos.append(pPositron.pT())

                # Z boson kinematics
                reconstructed_Z_mass = (pElectron + pPositron).mCalc()
                reconstructed_Z_masses.append(reconstructed_Z_mass)
                z_mass_og.append(mass_z)
                z_pt_og.append((pElectron + pPositron).pT())

"""# Paso 4: Graficar y analizar resultados"""

# ejecute esta celda para ver los histogramas resultantes de los datos que acaba de generar
fig, axs = plt.subplots(2, 2, figsize=(15, 14), subplot_kw={'aspect': 'auto'})

hist_mass_Z, bins_mass_Z, _ = axs[0, 0].hist(z_mass_og, bins=20, range=(60, 120))
axs[0, 0].set_title('Z Boson mass')
axs[0, 0].set_xlabel('$m_Z$  [GeV]')
axs[0, 0].set_ylabel('Eventos')

# histogram of reconstructed Z boson mass
hist_reco_Z_mass, bins_reco_Z_mass, _ = axs[0, 1].hist(reconstructed_Z_masses, bins=20, range=(60, 120)) #, histtype='step')
axs[0, 1].set_xlabel('$m_Z$  [GeV]')
axs[0, 1].set_ylabel('Eventos')
axs[0, 1].set_title('Reco Z Boson Mass')

# histogram of z pt
hist_pt_z, bins_pt_z, _ = axs[1, 0].hist(z_pt_og, bins=20)#, range=(60, 120))
axs[1, 0].set_xlabel('$p_T$ [GeV]')
axs[1, 0].set_ylabel('Eventos')
axs[1, 0].set_title('Z boson $p_T$')

# electron variables
#  pt for Electron
hist_pt_e, bins_pt_e, _ = axs[1, 1].hist(pT_e, bins=20)
axs[1, 1].set_title('pT for Electron')
axs[1, 1].set_xlabel('$p_T$ [GeV]')
axs[1, 1].set_ylabel('Eventos')

"""# Ejercicios

- Dibujar el diagrama de Feynman a nivel de árbol para este proceso
- Cambiar la simulación para que en lugar de colisionar protones, colisione electrón VS positrón
- Investigar y agregar más variables cinemáticas de interés en experimentos de física de altas energías
- Reproduzca las condiciones de los futuros colisionadores de partículas (Ejemplo el ILC).
- **Reto:** Modificar la simulación para que en lugar de producir un bosón $Z$ se produzca un bosón cargado $W$
"""

